Develop v1.0
edwardivash/RSSReader pull request #1
Opened 2020-11-22 13:27 UTC by edwardivash

2020-11-22 18:04 UTC, trotnic commented on RSReader/RSSReader/View Controllers/FeedListVC.m
> +        });
- error case isn't handled

2020-11-23 09:08 UTC, AndreiChernyshou commented on RSReader/RSSReader/Models/Feeds.m
> +    self = [super init];
In this case you can pass nil as an incoming parameter. Does your code makes sense if dictionary is nil? I would suggest to double check it and introduce a protection against nil parameter.

2020-11-23 09:10 UTC, AndreiChernyshou commented on RSReader/RSSReader/Models/Feeds.m
> +        _pubDate = [[self parseDate:dictionary[@"pubDate"]]copy];
Looks like this operation is too heavy for initialization stage. I would suggest to implement factory and move all this configuration there.

2020-11-23 09:17 UTC, AndreiChernyshou commented on RSReader/RSSReader/Models/Feeds.m
> +    NSDateFormatter *oldFormatter = [NSDateFormatter new];
You are violating single responsibility principle here. Your function is expected to parse some data but you also create and configure date formatter inside. Please, create lazy loading function for the creation of the date formatter and its configuration.

2020-11-23 09:22 UTC, AndreiChernyshou commented on RSReader/RSSReader/Services/FeedService.m
> +            [parser parseFeeds:data completion:completion];
SRP (Single responsibility principle) violation. In this function your are supposed to load data. You should not perform parsing inside it. Please, move parsing out of the function scope.

2020-11-23 09:23 UTC, AndreiChernyshou commented on RSReader/RSSReader/Support/AppDelegate.m
> +    FeedListVC *vc = [[FeedListVC alloc]init];
You can use just FeedListVC *vc = [FeedListVC new];

2020-11-23 09:23 UTC, AndreiChernyshou commented on RSReader/RSSReader/Support/AppDelegate.m
> +    FeedListVC *vc = [[FeedListVC alloc]init];
vc is a bad naming practice

2020-11-23 09:24 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedListVC.m
> +    UITableView *tableView = [[UITableView alloc]init];
Just implement lazy loading and move creation and all the configuration there.

2020-11-23 09:25 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedListVC.m
> +-(void)feedsLoader {
Just implement lazy loading and move creation and all the configuration there.

2020-11-23 09:26 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedListVC.m
> +    [self.feedService loadFeeds:^(NSArray<Feeds *> *feedsArray, NSError * error) {
SRP violation. You should not create, configure and call the created / configured element all in one call. Do it separately.

2020-11-23 09:30 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedListVC.m
> +    cell.feedItem = self.dataSource[indexPath.row];
No need to assign value to the cell and call configuration method after it. Just do it in one go like this:
[cell configureWithItem: self.dataSource[indexPath.row];

2020-11-23 09:35 UTC, AndreiChernyshou commented on RSReader/RSSReader/Views/FeedTableViewCell.m
> +    self.feedLabel.text = feed.title;
You should perform configuration based on internal property rather that input parameter.
 -(void)configureFeedItem:(Feeds *)feed {
    self.feedItem = feed;
    self.feedLabel.text = self.feedItem.title;
  self.pubDateLabel.text = self.feedItem.pubDate;
}

2020-11-23 09:36 UTC, AndreiChernyshou commented on RSReader/RSSReader/XMLParser/RSXmlParser.m
> +    NSXMLParser *parser = [[NSXMLParser alloc]initWithData:data];
SRP violation. Move parser creation and configuration to the parser lazy loading call.

2020-11-23 09:38 UTC, AndreiChernyshou requested changes
Please review the comments and introduce required changes.

2020-11-25 16:29 UTC, trotnic reviewed
please, check the review and fix problems

2020-11-25 16:29 UTC, trotnic commented on RSReader/RSSReader/Services/LoadDataFromURL/FeedService.m
> +    NSURLSessionDataTask *dataTask = [session dataTaskWithRequest:request
you don't configure request, why not use `dataTaskWithURL:completionHandler:`?

2020-11-25 16:29 UTC, trotnic commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +}
you use `feed` object for configuring cell presentation only for a once, 
keep reference to it within cell class is excessive and should be removed

2020-11-25 16:29 UTC, trotnic commented on RSReader/RSSReader/Models/FeedsModel/Feeds.m
> +        self = [super init];
what happens in case when `self` is `nil`?

2020-11-25 16:29 UTC, trotnic commented on RSReader/RSSReader/XMLParser/RSXmlParser.m
> +        [parser release];
move parser creation and configuration in a category

2020-11-25 16:29 UTC, trotnic commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +@property (retain, nonatomic) FeedService *feedService;
you are tending to a massive view controller, leaving business logic here

2020-11-26 08:29 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +@property (retain, nonatomic)NSArray<Feeds*> *dataSource;
Space missed

2020-11-26 08:30 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +        _feedTableView = [UITableView new];
Please, move table view creation and configuration inside getter

2020-11-26 08:31 UTC, AndreiChernyshou commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.h
> +@property (retain,nonatomic) Feeds *feedItem;
Space is missed

2020-11-26 08:32 UTC, AndreiChernyshou commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +- (void)awakeFromNib {
What for do you need an empty override statement?

2020-11-26 08:58 UTC, AndreiChernyshou reviewed
Comments are not critical but desirable to be fixed

2020-12-02 07:18 UTC, trotnic commented on RSReader/RSSReader/Services/LoadDataFromURL/FeedService.h
> +@property (nonatomic, retain) id<RSParserProtocol> parser;
do you need to access this property from elsewhere in your application or you should move it to the corresponding extension?

2020-12-03 11:56 UTC, merged