finish 1.1 version
edwardivash/RSSReader pull request #2
Opened 2020-12-05 10:39 UTC by edwardivash

2020-12-14 15:35 UTC, trotnic commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +                NSLog(@"Error - %@",error);
present an error instead of logging it

2020-12-14 15:35 UTC, trotnic commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +        self.feedService = [[[FeedService alloc]initWithParser:self.parser]autorelease];
make lazy property

2020-12-14 15:35 UTC, trotnic commented on RSReader/Categories/UIBarButtonItem/UIBarButtonItem+ActivityIndicator.m
> +}
this method creates UIBarButtonItem object & creates indicator & manages indicator animation 
srp violation obviously

2020-12-21 09:19 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +                NSLog(@"Error - %@",error);
fixed

2020-12-21 09:19 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +        self.feedService = [[[FeedService alloc]initWithParser:self.parser]autorelease];
fixed

2020-12-21 09:19 UTC, edwardivash commented on RSReader/Categories/UIBarButtonItem/UIBarButtonItem+ActivityIndicator.m
> +}
fixed

2021-01-13 09:57 UTC, AndreiChernyshou requested changes

2021-01-13 09:57 UTC, AndreiChernyshou commented on RSReader/Categories/UIAlertController/UIAlertController+ShowAlertController.m
> +    UIAlertController *alert = [UIAlertController alertControllerWithTitle:[NSString stringWithFormat:@"%@", error] message:@"Check your internet connection." preferredStyle:UIAlertControllerStyleAle
Please, use localized strings for text messages.

2021-01-13 09:57 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +                    [weakSelf.navigationItem setRightBarButtonItem:[UIBarButtonItem setupBarButtonItem:_activityIndicator animating:NO]];
There three similar lines of code inside one func:
[weakSelf.navigationItem setRightBarButtonItem:[UIBarButtonItem setupBarButtonItem:_activityIndicator animating:NO]];

probably, there is a way to make this code reusable.

2021-01-15 20:55 UTC, OrientCue commented on RSReader/Categories/UIAlertController/UIAlertController+ShowAlertController.h
> ++(UIAlertController *)showAlertController:(NSError *)error;
Alert message isn't good.
Infinite activity scrolling after error.
How to force reload feed after alert have been dismissed?

https://user-images.githubusercontent.com/48133328/104777527-db3a4880-578c-11eb-8d92-96d94886f9cb.mov

2021-01-15 21:02 UTC, OrientCue commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +    [NSThread detachNewThreadSelector:@selector(feedsLoader) toTarget:self withObject:nil];
Download data and parsing performed on Thread 3 Queue : com.apple.NSURLSession-delegate (serial), not on thread you detached.

2021-01-15 21:04 UTC, OrientCue commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +                self.dataSource = feedsArray;
`self` inside block.

2021-01-15 21:18 UTC, OrientCue commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +        [weakSelf.navigationItem setRightBarButtonItem:[UIBarButtonItem setupBarButtonItem:_activityIndicator animating:YES]];
Alloc-init ivar `_activityIndicator` inside method of UIBarButton category `-setupBarButtonItem:`. It is created every time you called this method.  Probably you should initialize this ivar in this class, if it actually needed. Maybe store UIBarButtonItem property with activity indicator.

2021-01-22 17:07 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +        [weakSelf.navigationItem setRightBarButtonItem:[UIBarButtonItem setupBarButtonItem:_activityIndicator animating:YES]];
fixed

2021-01-22 17:07 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +                self.dataSource = feedsArray;
fixed

2021-01-22 17:07 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +    [NSThread detachNewThreadSelector:@selector(feedsLoader) toTarget:self withObject:nil];
fixed

2021-01-22 17:07 UTC, edwardivash commented on RSReader/Categories/UIAlertController/UIAlertController+ShowAlertController.h
> ++(UIAlertController *)showAlertController:(NSError *)error;
fixed

2021-01-22 17:07 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +                    [weakSelf.navigationItem setRightBarButtonItem:[UIBarButtonItem setupBarButtonItem:_activityIndicator animating:NO]];
fixed

2021-01-22 17:07 UTC, edwardivash commented on RSReader/Categories/UIAlertController/UIAlertController+ShowAlertController.m
> +    UIAlertController *alert = [UIAlertController alertControllerWithTitle:[NSString stringWithFormat:@"%@", error] message:@"Check your internet connection." preferredStyle:UIAlertControllerStyleAle
fixed

2021-01-22 20:44 UTC, OrientCue commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +- (void)refreshButtonAction {
Tap on refresh button did not force download feed.

2021-01-22 21:04 UTC, OrientCue commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +                    [weakSelf presentViewController:[UIAlertController showAlertControllerWithAction:self] animated:YES completion:nil];
`self` inside block.
Probably you should `stopAnimating` activity before presenting alert and show refresh. Thus you can create alert without parameter (use here received `error` if needed). 
Bad naming for method `showAlertControllerWithAction:` you create alert there, not show.

2021-01-22 21:08 UTC, OrientCue commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +    self.refreshButton.image = [UIImage imageNamed:kRefreshButtonName];
Move configuration to lazy property.

2021-01-22 21:10 UTC, OrientCue commented on RSReader/Categories/UIAlertController/UIAlertController+ShowAlertController.m
> +    UIAlertController *alert = [UIAlertController alertControllerWithTitle:NSLocalizedString(@"Unable to load data.", @"") message:NSLocalizedString(@"Check your internet connection.", @"") preferred
Please move NSString literals to global constants.

2021-01-24 18:12 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +- (void)refreshButtonAction {
fixed

2021-01-24 18:12 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +                    [weakSelf presentViewController:[UIAlertController showAlertControllerWithAction:self] animated:YES completion:nil];
fixed

2021-01-24 18:12 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +    self.refreshButton.image = [UIImage imageNamed:kRefreshButtonName];
fixed

2021-01-24 18:12 UTC, edwardivash commented on RSReader/Categories/UIAlertController/UIAlertController+ShowAlertController.m
> +    UIAlertController *alert = [UIAlertController alertControllerWithTitle:NSLocalizedString(@"Unable to load data.", @"") message:NSLocalizedString(@"Check your internet connection.", @"") preferred
fixed

2021-01-28 12:03 UTC, AndreiChernyshou approved these changes

2021-01-28 13:18 UTC, merged