Develop v1.2
edwardivash/RSSReader pull request #4
Opened 2021-02-03 13:17 UTC by edwardivash

2021-02-04 08:57 UTC, AndreiChernyshou requested changes

2021-02-04 08:57 UTC, AndreiChernyshou commented on RSReader/Categories/NSStringSubstring/NSString+GetSubstringFromDescription.m
> +    NSString *result = [descriptiongString substringWithRange:rSub];
What for do you create an extra local variable? Just:
return [descriptiongString substringWithRange:rSub];

2021-02-04 08:57 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +    cell.descriptionButton.tag = indexPath.row;
That is a disclosure of cell implementation details to the view controller. All the cell configuration should happen internally.

2021-02-04 08:57 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +    [cell.descriptionButton addTarget:self action:@selector(setButtonStateAction:) forControlEvents:UIControlEventTouchUpInside];
That is a bad approach.
1. Use blocks
2. Create a configuration object and pass completion inside the -configure call

2021-02-04 08:57 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +    if ([self.selectedButtonsRows containsObject:indexPath]) {
There is too match code here, let's make it shorter:

Bool isContained = [self.selectedButtonsRows containsObject:indexPath];
UIImage *image = isContained ? [UIImage imageNamed:kSelectedImageName] : [UIImage imageNamed:kDisabledImageName];
[cell.descriptionButton setImage: image];

You can use another naming but the idea should be the same.
[cell.descTextView setHidden: !isContained];

2021-02-04 08:57 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +    if ([self.selectedButtonsRows containsObject:indexPath]) {
The same:
Bool isContained = [self.selectedButtonsRows containsObject:indexPath]
return isContained ? extendedCellSize : UITableViewAutomaticDimension;

2021-02-04 08:57 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +    if ([sender isSelected]) {
Please, fix according to the comments above.

2021-02-04 08:57 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/WebViewController/WebViewController.m
> +-(UIWebView *)webView {
Every time the function is called you will receive a new web view. Is it what you expect?

2021-02-04 08:57 UTC, AndreiChernyshou commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +        [NSLayoutConstraint activateConstraints:@[
Its a bad idea to set constraints here.
1. It is not evident
2. what if I need to get a text view and put it into the stack view or position it with frame?

2021-02-16 07:41 UTC, AndreiChernyshou requested changes
Please, fix all the comments

2021-02-16 07:41 UTC, AndreiChernyshou commented on RSReader/Categories/NSStringSubstring/NSString+GetSubstringFromDescription.h
> ++ (NSString *)descriptionsSubstring:(NSString *)descriptiongString;
Please, use a more meaningful naming. func name should explain what happens inside. I need to dive into it to understand what happens now.

2021-02-16 07:41 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +    [cell changeFeedTableCellButtonState:indexPath array:self.selectedButtonsRows block:^(UIButton *button) {
Too many cell details exposed. View controller should know nothing about cell state. You should just pass some date and the cell should handle it internally.

2021-02-16 07:41 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +- (void)setButtonStateAction:(UIButton *)sender {
The same.

2021-02-16 07:41 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/WebViewController/WebViewController.m
> +-(void)safariAction {
Single responsibility principle violation. Pop to root is not expected here

2021-02-16 07:41 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/WebViewController/WebViewController.m
> +- (void)customizeWebViewInWebViewVC {
SRP violation. Web view creation is not expected inside -customise call as well as constraints creation. What will happen if we call it within or prior -viewDidLoad?

2021-02-16 07:41 UTC, AndreiChernyshou commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +- (void)changeFeedTableCellButtonState:(NSIndexPath *)indexPath array:(NSMutableArray *)array block:(void (^)(UIButton *button)) blockName {
Block name should be meaningful.

2021-02-16 07:41 UTC, AndreiChernyshou commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +    blockName(weakSelf.descriptionButton);
what will happen if nil would be passed instead of block?

2021-02-16 07:41 UTC, AndreiChernyshou commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +        [self.contentView addSubview:_descTextView];
Violation of SRP. Why do you add view to the super view inside getter?

2021-02-20 09:01 UTC, OrientCue requested changes
Please fix comments.

2021-02-21 22:50 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/WebViewController/WebViewController.m
> +    [self setToolbarItems:[NSArray arrayWithObjects:self.backButton,self.barButtonsSeparater,
Fixed

2021-02-21 22:50 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/WebViewController/WebViewController.m
> +@property (nonatomic, retain) UIWebView *webView;
Fixed

2021-02-21 22:50 UTC, edwardivash commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +@property (retain, nonatomic) IBOutlet UIButton *descriptionButton;
Fixed

2021-02-21 22:50 UTC, edwardivash commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +        [self.contentView addSubview:_descTextView];
Fixed

2021-02-21 22:50 UTC, edwardivash commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +    blockName(weakSelf.descriptionButton);
Fixed

2021-02-21 22:51 UTC, edwardivash commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +- (void)changeFeedTableCellButtonState:(NSIndexPath *)indexPath array:(NSMutableArray *)array block:(void (^)(UIButton *button)) blockName {
Fixed

2021-02-21 22:51 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/WebViewController/WebViewController.m
> +- (void)customizeWebViewInWebViewVC {
Fixed

2021-02-21 22:51 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/WebViewController/WebViewController.m
> +-(void)safariAction {
Fixed

2021-02-21 22:51 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +- (void)setButtonStateAction:(UIButton *)sender {
Fixed

2021-02-21 22:51 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +    [cell changeFeedTableCellButtonState:indexPath array:self.selectedButtonsRows block:^(UIButton *button) {
Fixed

2021-02-21 22:51 UTC, edwardivash commented on RSReader/Categories/NSStringSubstring/NSString+GetSubstringFromDescription.h
> ++ (NSString *)descriptionsSubstring:(NSString *)descriptiongString;
Fixed

2021-02-21 23:22 UTC, OrientCue commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +@property (retain, nonatomic) IBOutlet UIButton *descriptionButton;
## Still too much empty space at toggled state.  I think cell height should be changed depending on state.

![toggled state](https://user-images.githubusercontent.com/48133328/108642093-470e8000-74b4-11eb-8cf5-a6b00c076007.png)
![expanded state](https://user-images.githubusercontent.com/48133328/108642096-483fad00-74b4-11eb-9238-30853a7e8e01.png)

2021-02-22 09:13 UTC, AndreiChernyshou requested changes
Please, fix the comments

2021-02-22 09:13 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +            });
you are duplicating the same calls within if...else condition:
    [weakSelf.activityIndicator stopAnimating];
    [weakSelf setupRefreshButton];
Since they are called either way just move them out of the if...else statement

2021-02-22 09:13 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +            [cell.contentView layoutSubviews];
You can call it just on cell and it will pass the call to all of it's subviews.

2021-02-22 09:13 UTC, AndreiChernyshou commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +    BOOL isContains = [self.selectedButtons containsObject:indPath];
You are still storing the state of the item inside separate array. It would be better to make it a part of the data source item you use to configure cell.

2021-02-22 09:13 UTC, AndreiChernyshou commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +    BOOL isContains = [self.selectedButtons containsObject:indPath];
isContains sounds wrong in English. A better option would be isContained.

2021-02-22 09:13 UTC, AndreiChernyshou commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +    isContained ? [self.descTextView setHidden:NO] : [self.descTextView setHidden:YES];
Just pass !isContained as a parameter. Tertiary operator is excessive here.

2021-02-22 20:07 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +            });
Fixed

2021-02-22 20:07 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/FeedsTableViewVC/FeedListVC.m
> +            [cell.contentView layoutSubviews];
Fixed

2021-02-22 20:08 UTC, edwardivash commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +    BOOL isContains = [self.selectedButtons containsObject:indPath];
Fixed

2021-02-22 20:08 UTC, edwardivash commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +    BOOL isContains = [self.selectedButtons containsObject:indPath];
Fixed

2021-02-22 20:08 UTC, edwardivash commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +    isContained ? [self.descTextView setHidden:NO] : [self.descTextView setHidden:YES];
Fixed

2021-02-22 20:08 UTC, edwardivash commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +@property (retain, nonatomic) IBOutlet UIButton *descriptionButton;
Fixed

2021-02-23 09:59 UTC, OrientCue commented
Problem with toggled/expanded state of cell.

https://user-images.githubusercontent.com/48133328/108827503-be3c3500-75d6-11eb-95fd-cdcd8ad62450.mov

2021-02-26 16:05 UTC, edwardivash commented on RSReader/RSSReader/Views/FeedTableViewCell/FeedTableViewCell.m
> +@property (retain, nonatomic) IBOutlet UIButton *descriptionButton;
Fixed

2021-03-02 13:58 UTC, AndreiChernyshou approved these changes

2021-03-02 16:51 UTC, merged