Develop v1.3
edwardivash/RSSReader pull request #5
Opened 2021-03-02 18:36 UTC by edwardivash

2021-03-03 11:35 UTC, OrientCue requested changes
There are no enhancements from v1.2 (annotation button on cell).
Missed handling website url with http scheme and direct link to feed. 
Please fix comments.

2021-03-03 11:35 UTC, OrientCue commented on RSReader/Categories/ErrorAlertController/UIAlertController+ErrorAlertController.m
> +@implementation UIAlertController (ErrorAlertController)
There are a lot of repeated code here. Don't repeat yourself.
**DRY violation.**

2021-03-03 11:35 UTC, OrientCue commented on RSReader/Categories/ErrorAlertController/UIAlertController+ErrorAlertController.m
> +    UIAlertController *errorAlertController = [UIAlertController alertControllerWithTitle:@"Wrong URL format." message:@"Example: https://news.tut.by \nor https://tut.by/rss" preferredStyle:UIAlertCo
Please use localized strings for text which is displayed to user.

2021-03-03 11:35 UTC, OrientCue commented on RSReader/Categories/ErrorAlertController/UIAlertController+ErrorAlertController.m
> +    UIAlertAction *okAction = [UIAlertAction actionWithTitle:@"Ok" style:UIAlertActionStyleCancel handler:nil];
same

2021-03-03 11:35 UTC, OrientCue commented on RSReader/Categories/ErrorAlertController/UIAlertController+ErrorAlertController.m
> +    UIAlertController *errorAlertController = [UIAlertController alertControllerWithTitle:@"This channel already exists." message:@"Enter a new URL for a channel." preferredStyle:UIAlertControllerSty
same

2021-03-03 11:35 UTC, OrientCue commented on RSReader/Categories/ErrorAlertController/UIAlertController+ErrorAlertController.m
> +    UIAlertController *errorAlertController = [UIAlertController alertControllerWithTitle:@"It is not possible to download data from this RSS feed channel." message:@"Please edit url." preferredStyle
same

2021-03-03 11:35 UTC, OrientCue commented on RSReader/Categories/RSSAlertController/UIAlertController+RSSAlertController.m
> +    UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"Add RSS Channel" message:@"" preferredStyle:UIAlertControllerStyleAlert];
Please use localized alert messages.

2021-03-03 11:35 UTC, OrientCue commented on RSReader/Categories/RSSAlertController/UIAlertController+RSSAlertController.m
> +        textFieldURL.placeholder = @"Please enter your URL";
This text should be localized.

2021-03-03 11:35 UTC, OrientCue commented on RSReader/Categories/RSSAlertController/UIAlertController+RSSAlertController.m
> ++ (UIAlertController *)addWebSite:(RSSViewController *)rssVC {
Missleading method name.
**SRP violation.**

2021-03-03 11:35 UTC, OrientCue commented on RSReader/RSSReader/HtmlParser/HtmlParser.m
> +    NSTextCheckingResult *match = [regex firstMatchInString:stringChannel
Handling only one feed from website.

2021-03-03 11:35 UTC, OrientCue commented on RSReader/RSSReader/HtmlParser/HtmlParser.m
> +    NSRegularExpression *regex = [NSRegularExpression regularExpressionWithPattern:@"https://[a-z0-9]+.[a-z0-9./]+(rss|feed|xml)"
It is possible that feed doesn't match this pattern. Look carefull task description and search here for tag `<link rel="alternate" type="application/rss+xml"`

2021-03-04 15:22 UTC, AndreiChernyshou approved these changes

2021-03-04 15:22 UTC, AndreiChernyshou commented on RSReader/RSSReader/View Controllers/RSSViewController/RSSViewController.m
> +    if (editing && !self.rssTableView.isEditing) {
It should be done the other way:

Bool isEditing = editing && !self.rssTableView.isEditing;
[self.rssTableView setEditing: isEditing animated: isEditing]

2021-03-07 17:27 UTC, edwardivash commented on RSReader/RSSReader/View Controllers/RSSViewController/RSSViewController.m
> +    if (editing && !self.rssTableView.isEditing) {
Fixed

2021-03-09 14:08 UTC, AndreiChernyshou approved these changes

2021-03-09 15:12 UTC, merged